#lang racket
(define (copyfile infile outfile)
  (let ((inport (open-input-file infile))
        (outport (open-output-file outfile)))
    (copy inport outport)
    (close-input-port inport)
    (close-output-port outport)
    'done
    )
  )
(define (copy inp outp)
  (let ((c (read-char inp)))
    (if (eof-object? c)
        '( )
        (begin (write-char c outp) (copy inp outp))
        )
    )
  )
(copyfile "input.txt" "output.txt")